#!/bin/bash

# TTY
sudo mkdir /etc/sddm.conf.d
sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf.d/default.conf

# Changer la ligne "DisplayServer=x11" par "DisplayServer=wayland"
sudo sed -i 's/DisplayServer=x11/DisplayServer=wayland/' /etc/sddm.conf.d/default.conf

# Changer la ligne "ReuseSession=true" par "ReuseSession=false"
sudo sed -i 's/ReuseSession=true/ReuseSession=false/' /etc/sddm.conf.d/default.conf

# Ajouter au script de demarrage de sddm:
# export XDG_CURRENT_DESKTOP=

# Copier dans .config et editer la config hyprland.conf
cp /usr/share/
# Decommenter la ligne "exec_once = waybar & hyprland & firefox"

# Ajouter a la ligne "monitor = " le nom de l'ecran (ici: Virtual1,1920x1080@60, auto, auto)

# Enlever ligne "autogenerated=1" pour enlever yellow warning des shortcuts